CREATE TABLE ts_category (
	'id' INTEGER PRIMARY KEY,
	'name' NVARCHAR NOT NULL
);

CREATE TABLE ats_type (
	'id' INTEGER PRIMARY KEY AUTOINCREMENT,
	'ts_id' INTEGER  NOT NULL,
	'name' NVARCHAR NOT NULL
);

CREATE TABLE car (
  'id' INTEGER PRIMARY KEY AUTOINCREMENT,
  'uid' NVARCHAR NOT NULL,
  'marka' NVARCHAR
);
